### ISSUE TITLE
Issue #1 - User can enter up to 8 binary digits in one input field.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/bin-2-dec-calc#3]
## 💰 Feature

User can enter up to 8 binary digits in one input field.

## 🗒️ Notes

This will require me to create a new component which will contain the calculator UI.

## ✅ Tasks

- [x] Create a component to contain the calculator UI.
- [x] Add an input area for the binary input.
- [x] Add a limit so no more than 8 numbers can be input (for now).
- [x] Add some styling.
- [x] Test, polish, kill all bugs.
