### ISSUE TITLE
Issue #2 - User must be notified if anything other than a 0 or 1 was entered.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/bin-2-dec-calc#4]
## 💰 Feature

User must be notified if anything other than a 0 or 1 was entered.

## 🗒️ Notes
 
This will require me to create a function which tests the input with regex to determine whether any character is not a 0 or 1.

## ✅ Tasks

- [x] Create a function (isNotBinary) that tests whether anything other than a 0 or 1 was entered.
- [x] Create regex, and call function in handleChange method.
- [x] If the test passes (there is something besides 0 or 1), add an error message to the output.
- [x] Test, polish, kill all bugs.
