### ISSUE TITLE
Issue #3 - User can view the results in a single output field

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/bin-2-dec-calc#5]
## 💰 Feature

 User can view the results in a single output field.

## 🗒️ Notes

This will require me to create a function which calculates the decimal conversion of the binary input, and renders it. 

## ✅ Tasks
- [x] Create a function (calculateDecimal) which calculates the decimal value from the binary input.
- [x] If the call to isNotBinary returns false, call the calculateDecimal function and assign the return to output.
- [x] Test, polish, kill all bugs.
